apiVersion: apps/v1
kind: Deployment
metadata:
  name: asgbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asgbuggy
  template:
    metadata:
      labels:
        app: asgbuggy
    spec:
      containers:
      - name: asgbuggy
        image: 853504916271.dkr.ecr.us-east-1.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: asgbuggy
#     k8s-app: asgbuggy
#   name: asgbuggy
# spec:
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   type: LoadBalancer
#   selector:
#     app: asgbuggy

apiVersion: v1
kind: Service
metadata:
  labels:
    app: asgbuggy
    k8s-app: asgbuggy
  name: asgbuggy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: asgbuggy
